In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
pd.set_option('display.max_columns', 22)
pd.set_option('display.max_rows', 300)

In [2]:
data = pd.read_csv("../data_sets/Employee_Compensation_SF.csv")

In [3]:
data.head()

,Year Type,Year,Organization Group Code,Organization Group,Department Code,Department,Union Code,Union,Job Family Code,Job Family,Job Code,Job,Employee Identifier,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
0,Fiscal,2016,1,Public Protection,DAT,District Attorney,311.0,Municipal Attorneys' Association,8100,Legal & Court,8177,Attorney (Civil/Criminal),49919,114473.16,0.0,1500.00,115973.16,21025.98,13068.80,9368.71,43463.49,159436.65
1,Calendar,2013,5,Culture & Recreation,ART,Arts Commission,790.0,"SEIU - Miscellaneous, Local 1021",1800,"Budget, Admn & Stats Analysis",1844,Senior Management Assistant,1225,84077.11,0.0,0.00,84077.11,16587.30,12457.73,6931.91,35976.94,120054.05
2,Calendar,2015,4,Community Health,DPH,Public Health,535.0,"SEIU - Human Services, Local 1021",2900,Human Services,2903,Eligibility Worker,34873,9980.17,0.0,798.43,10778.60,0.00,2254.93,835.11,3090.04,13868.64
3,Fiscal,2015,4,Community Health,DPH,Public Health,250.0,"SEIU - Health Workers, Local 1021",2200,Medical & Dental,2202,Dental Aide,51145,2873.41,0.0,0.00,2873.41,0.00,622.63,222.46,845.09,3718.50
4,Fiscal,2014,5,Culture & Recreation,REC,Recreation and Park Commission,790.0,"SEIU - Miscellaneous, Local 1021",3200,Recreation,3279,Recreation Leader,48705,6701.85,0.0,176.70,6878.55,0.00,2711.66,538.43,3250.09,10128.64

In [4]:
data.shape

(291825, 22)

In [5]:
data.columns

Index(['Year Type', 'Year', 'Organization Group Code', 'Organization Group',
       'Department Code', 'Department', 'Union Code', 'Union',
       'Job Family Code', 'Job Family', 'Job Code', 'Job',
       'Employee Identifier', 'Salaries', 'Overtime', 'Other Salaries',
       'Total Salary', 'Retirement', 'Health/Dental', 'Other Benefits',
       'Total Benefits', 'Total Compensation'],
      dtype='object')

In [6]:
print(len(data.columns))

22

In [7]:
le = LabelEncoder()
data['Organization Group']= le.fit_transform(data['Organization Group'])

In [8]:
data.drop(data.columns[[0, 4, 5, 7, 8, 9, 10, 11]], axis = 1, inplace = True)

In [9]:
data.head(100)

,Year,Organization Group Code,Organization Group,Union Code,Employee Identifier,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
0,2016,1,5,311.0,49919,114473.16,0.00,1500.00,115973.16,21025.98,13068.80,9368.71,43463.49,159436.65
1,2013,5,1,790.0,1225,84077.11,0.00,0.00,84077.11,16587.30,12457.73,6931.91,35976.94,120054.05
2,2015,4,0,535.0,34873,9980.17,0.00,798.43,10778.60,0.00,2254.93,835.11,3090.04,13868.64
3,2015,4,0,250.0,51145,2873.41,0.00,0.00,2873.41,0.00,622.63,222.46,845.09,3718.50
4,2014,5,1,790.0,48705,6701.85,0.00,176.70,6878.55,0.00,2711.66,538.43,3250.09,10128.64
5,2013,2,6,21.0,19801,45321.18,0.00,0.00,45321.18,9386.03,11780.60,3486.34,24652.97,69974.15
6,2015,5,1,790.0,14135,28305.50,0.00,1193.14,29498.64,6616.52,5793.48,2430.74,14840.74,44339.38
7,2014,6,2,21.0,37352,39938.09,0.00,800.00,40738.09,8685.34,7269.02,3277.52,19231.88,59969.97
8,2015,1,5,911.0,13380,23112.00,2312.73,20944.16,46368.89,4183.12,1911.46,68.84,6163.42,52532.31
9,2014,1,5,498.0,46569,89101.22,6856.77,5563.78,101521.77,17596.33,12512.55,1627.91,31736.79,133258.56
10,2015,2,6,790.0,38170,7091.33,0.00,0.00,7091.33,0.00,2361.82,549.01,2910.83,10002.16
11,2013,2,6,21.0,28940,57467.12,355.65,0.00,57822.77,11901.38,11933.98,4691.34,28526.70,86349.47
12,2015,5,1,261.0,10817,80357.00,5612.97,7.90,85977.87,16562.14,12424.50,7091.69,36078.33,122056.20
13,2013,2,6,253.0,21370,64170.89,13128.97,2677.81,79977.67,17109.68,13379.17,6204.01,36692.86,116670.53
14,2016,3,4,22.0,37341,83038.01,0.00,200.00,83238.01,15490.62,13068.80,6525.06,35084.48,118322.49
15,2014,6,2,16.0,34486,92530.82,0.00,13412.58,105943.40,20224.21,13054.94,8450.17,41729.32,147672.72
16,2015,2,6,253.0,4273,44381.77,11166.58,2694.49,58242.84,13602.20,8826.10,4423.70,26852.00,85094.84
17,2014,2,6,790.0,13061,78639.30,20332.03,7821.87,106793.20,17683.84,12512.54,8707.07,38903.45,145696.65
18,2014,1,5,311.0,10747,176267.41,0.00,1250.00,177517.41,36959.07,12512.55,10479.18,59950.80,237468.21
19,2015,2,6,38.0,37594,100655.41,8240.09,16911.85,125807.35,24354.06,12500.56,9962.73,46817.35,172624.70
20,2016,4,0,791.0,49930,57272.29,0.00,9765.52,67037.81,0.00,4171.29,3334.90,7506.19,74544.00
21,2015,3,4,535.0,39898,85368.06,307.40,659.00,86334.46,17731.18,12424.50,6989.63,37145.31,123479.77
22,2013,5,1,4.0,12884,66924.09,8749.42,2356.40,78029.91,13643.22,11083.02,6452.96,31179.20,109209.11
23,2015,4,0,791.0,22337,852.23,0.00,0.00,852.23,2322.44,0.00,759.54,3081.98,3934.21
24,2014,4,0,250.0,11367,58535.08,713.52,7502.19,66750.79,13854.97,11221.47,5241.67,30318.11,97068.90
25,2013,3,4,790.0,13130,28926.00,0.00,0.00,28926.00,5990.58,8862.78,2311.94,17165.30,46091.30
26,2016,4,0,250.0,53022,50527.16,868.12,2433.27,53828.55,11112.94,12535.71,4378.62,28027.27,81855.82
27,2015,3,4,1.0,38672,20258.75,0.00,906.70,21165.45,1771.07,8758.68,1714.73,12244.48,33409.93
28,2013,1,5,790.0,51618,51015.01,3572.78,871.20,55458.99,10565.26,12801.79,4510.65,27877.70,83336.69
29,2013,4,0,21.0,39302,40786.37,0.00,0.00,40786.37,7427.15,7718.01,3306.08,18451.24,59237.61
30,2014,4,0,21.0,6226,125662.01,0.00,17420.56,143082.57,26840.33,13054.94,10034.09,49929.36,193011.93
31,2014,4,0,790.0,44217,76052.02,880.20,3660.15,80592.37,16829.03,13054.94,6638.31,36522.28,117114.65
32,2013,3,4,535.0,25617,95229.04,0.00,6201.67,101430.71,19926.27,12918.24,8366.84,41211.35,142642.06
33,2015,3,4,790.0,39500,47730.89,0.00,521.01,48251.90,10822.86,10397.19,3789.77,25009.82,73261.72
34,2014,5,1,790.0,2196,2866.87,0.00,8.34,2875.21,0.00,988.79,222.60,1211.39,4086.60
35,2016,4,0,39.0,49055,13292.80,0.00,1080.08,14372.88,653.75,1995.23,1120.17,3769.15,18142.03
36,2014,1,5,911.0,3327,137982.08,28686.53,42125.20,208793.81,29979.70,13054.94,428.25,43462.89,252256.70
37,2016,5,1,790.0,30570,16345.50,0.00,753.39,17098.89,0.00,6428.42,1327.23,7755.65,24854.54
38,2015,2,6,21.0,14181,78718.90,0.00,0.00,78718.90,17656.73,12500.56,6281.72,36439.01,115157.91
39,2015,1,5,790.0,1454,67286.16,3656.69,2337.32,73280.17,15505.03,12512.53,5803.18,33820.74,107100.91
40,2015,5,1,790.0,48092,904.06,0.00,14.31,918.37,0.00,491.31,71.10,562.41,1480.78
41,2014,2,6,790.0,8516,46738.58,15629.12,2022.76,64390.46,10171.68,10077.10,5062.26,25311.04,89701.50
42,2015,2,6,790.0,34336,62811.00,7539.33,8382.41,78732.74,14020.17,12424.50,6469.20,32913.87,111646.61
43,2013,2,6,856.0,13987,71781.50,1588.20,1325.00,74694.70,14374.07,12918.25,5663.19,32955.51,107650.21
44,2014,3,4,790.0,42388,56261.25,0.00,599.45,56860.70,12122.70,11974.47,4706.05,28803.22,85663.92
45,2013,1,5,911.0,2594,8200.80,0.00,0.00,8200.80,1452.37,1181.70,633.57,3267.64,11468.44
46,2014,4,0,21.0,19787,24336.60,0.00,728.88,25065.48,0.00,1926.56,1940.57,3867.13,28932.61
47,2013,4,0,790.0,10687,44603.56,0.00,0.00,44603.56,8122.35,10487.92,3690.56,22300.83,66904.39
48,2013,2,6,21.0,36845,72097.73,0.00,0.00,72097.73,14276.97,11734.07,5855.16,31866.20,103963.93
49,2015,4,0,791.0,16287,64134.67,0.00,250.00,64384.67,12550.62,5636.72,5406.60,23593.94,87978.61
50,2014,4,0,790.0,45572,145857.03,749.89,2290.73,148897.65,31274.54,13054.94,10123.50,54452.98,203350.63
51,2013,3,4,1.0,5554,10727.70,0.00,272.29,10999.99,0.00,5083.78,851.62,5935.40,16935.39
52,2013,3,4,1.0,7581,207.80,0.00,0.00,207.80,0.00,98.48,16.09,114.57,322.37
53,2013,3,4,1.0,32552,11121.11,0.00,408.94,11530.05,0.00,5095.53,892.66,5988.19,17518.24
54,2015,1,5,911.0,21838,138645.53,42631.22,14334.25,195611.00,30525.24,12512.53,477.11,43514.88,239125.88
55,2013,1,5,798.0,9485,125192.74,6674.28,16602.74,148469.76,26907.42,14626.32,371.02,41904.76,190374.52
56,2015,4,0,250.0,9890,34355.95,540.07,2783.39,37679.41,5935.65,9157.09,2843.73,17936.47,55615.88
57,2013,1,5,356.0,45541,94705.32,0.00,0.00,94705.32,16772.24,11178.80,11816.92,39767.96,134473.28
58,2015,4,0,790.0,29631,82771.21,37146.64,7833.50,127751.35,17649.08,10560.83,9797.47,38007.38,165758.73
59,2015,1,5,911.0,26114,118826.97,11822.94,11618.73,142268.64,25676.99,0.00,2418.56,28095.55,170364.19
60,2015,4,0,250.0,3594,68373.27,5225.49,10005.32,83604.08,16727.85,12299.34,6814.15,35841.34,119445.42
61,2015,5,1,790.0,29083,61956.63,0.00,889.23,62845.86,13628.80,8171.50,5177.70,26978.00,89823.86
62,2013,2,6,21.0,29173,118014.02,0.00,1150.00,119164.02,21104.02,12801.79,9444.67,43350.48,162514.50
63,2014,2,6,253.0,17207,65822.79,22817.38,4795.99,93436.16,20265.87,13362.11,7326.64,40954.62,134390.78
64,2015,2,6,21.0,11661,89028.01,0.00,0.00,89028.01,18349.03,12424.48,6932.74,37706.25,126734.26
65,2014,1,5,911.0,8960,118898.01,4705.05,9828.69,133431.75,25699.92,13054.94,274.80,39029.66,172461.41
66,2013,3,4,535.0,12365,107082.12,1412.79,6360.26,114855.17,20924.62,12918.24,9373.41,43216.27,158071.44
67,2016,2,6,790.0,46338,68228.80,16460.26,4581.00,89270.06,12814.38,13068.80,7274.89,33158.07,122428.13
68,2015,1,5,911.0,27834,72324.00,0.00,91397.32,163721.32,15878.52,3345.06,4688.46,23912.04,187633.36
69,2016,1,5,790.0,26131,66378.75,36505.33,6125.47,109009.55,12914.28,8367.53,8674.79,29956.60,138966.15
70,2016,5,1,790.0,17079,882.00,0.00,0.00,882.00,0.00,448.92,68.45,517.37,1399.37
71,2015,4,0,791.0,20576,158276.28,0.00,5588.07,163864.35,27123.24,10502.29,7268.00,44893.53,208757.88
72,2014,2,6,6.0,13145,94305.02,1492.43,2164.23,97961.68,20825.72,13054.94,7551.38,41432.04,139393.72
73,2014,5,1,790.0,45475,20804.14,107.38,936.07,21847.59,0.00,5226.69,1691.44,6918.13,28765.72
74,2013,1,5,911.0,41032,59449.22,728.25,20242.08,80419.55,10860.16,6400.89,170.10,17431.15,97850.70
75,2013,3,4,790.0,42362,10967.00,0.00,0.00,10967.00,1997.10,2708.07,871.42,5576.59,16543.59
76,2013,4,0,790.0,31546,110017.42,5024.65,21235.56,136277.63,22032.43,12781.97,9401.58,44215.98,180493.61
77,2013,6,2,130.0,13797,43414.00,2616.47,40.72,46071.19,7913.10,6698.35,3824.53,18435.98,64507.17
78,2013,1,5,790.0,34637,87290.00,4832.91,12242.53,104365.44,18992.88,12858.44,8570.36,40421.68,144787.12
79,2015,2,6,790.0,29625,42915.13,251.92,271.44,43438.49,9640.21,8668.97,3512.85,21822.03,65260.52
80,2014,3,4,790.0,33562,40872.30,0.00,433.89,41306.19,8806.46,8667.03,3367.70,20841.19,62147.38
81,2013,1,5,911.0,24364,51193.18,0.00,2658.37,53851.55,9120.02,4739.12,894.93,14754.07,68605.62
82,2014,5,1,261.0,24491,62558.65,350.55,290.00,63199.20,13742.49,13054.96,5112.34,31909.79,95108.99
83,2015,4,0,790.0,42501,48609.20,11967.37,7985.61,68562.18,11773.34,11182.06,5616.08,28571.48,97133.66
84,2014,5,1,790.0,22910,20071.90,2491.92,0.00,22563.82,0.00,4842.02,1746.90,6588.92,29152.74
85,2015,5,1,16.0,28228,2482.90,0.00,0.00,2482.90,0.00,0.00,196.15,196.15,2679.05
86,2013,2,6,253.0,12459,25322.25,11833.11,1737.90,38893.26,7768.82,5130.22,3058.07,15957.11,54850.37
87,2015,3,4,1.0,29842,4226.50,0.00,0.00,4226.50,572.83,1891.84,327.22,2791.89,7018.39
88,2015,3,4,21.0,52291,90125.89,0.00,0.00,90125.89,20215.19,11105.62,7045.88,38366.69,128492.58
89,2015,3,4,790.0,33225,18887.80,0.00,100.00,18987.80,3533.65,3488.42,1505.67,8527.74,27515.54
90,2014,5,1,790.0,53753,13416.43,0.00,200.29,13616.72,0.00,3630.90,1054.20,4685.10,18301.82
91,2013,1,5,498.0,22230,91200.81,1217.60,4315.86,96734.27,18702.20,12801.79,1629.45,33133.44,129867.71
92,2013,4,0,791.0,20855,6620.05,0.00,0.00,6620.05,1294.75,741.61,581.97,2618.33,9238.38
93,2015,1,5,911.0,45118,82197.20,8107.97,6198.74,96503.91,16869.40,9079.44,1640.91,27589.75,124093.66
94,2014,1,5,911.0,3093,119613.76,43674.00,22972.14,186259.90,25127.25,13054.94,2981.33,41163.52,227423.42
95,2014,2,6,261.0,43529,195.10,0.00,2.44,197.54,0.00,47.95,15.29,63.24,260.78
96,2015,2,6,351.0,38696,157061.11,0.00,0.00,157061.11,34592.81,12500.56,18243.19,65336.56,222397.67
97,2015,4,0,21.0,22739,116860.81,0.00,0.00,116860.81,25639.24,12500.55,9276.94,47416.73,164277.54
98,2016,1,5,499.0,22515,139889.20,14996.74,17925.10,172811.04,37301.21,13068.80,2919.86,53289.87,226100.91
99,2013,6,2,22.0,18365,98811.00,0.00,0.00,98811.00,19423.66,12918.24,7894.14,40236.04,139047.04

In [10]:
data.shape

(291825, 14)

In [11]:
new_data = data.dropna()

In [12]:
new_data.shape

(291782, 14)

In [13]:
print(len(new_data.columns))

14

In [14]:
num = new_data._get_numeric_data()
num[num < 0] = 0
new_data.head()

,Year,Organization Group Code,Organization Group,Union Code,Employee Identifier,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
0,2016,1,5,311.0,49919,114473.16,0.0,1500.00,115973.16,21025.98,13068.80,9368.71,43463.49,159436.65
1,2013,5,1,790.0,1225,84077.11,0.0,0.00,84077.11,16587.30,12457.73,6931.91,35976.94,120054.05
2,2015,4,0,535.0,34873,9980.17,0.0,798.43,10778.60,0.00,2254.93,835.11,3090.04,13868.64
3,2015,4,0,250.0,51145,2873.41,0.0,0.00,2873.41,0.00,622.63,222.46,845.09,3718.50
4,2014,5,1,790.0,48705,6701.85,0.0,176.70,6878.55,0.00,2711.66,538.43,3250.09,10128.64

In [15]:
new_data['Organization Group'].unique()

array([5, 1, 0, 6, 2, 4, 3])

In [16]:
#np.isnan(data)

In [17]:
#np.where(np.isnan(data))

In [18]:
#np.nan_to_num(data)

In [19]:
#new_data[new_data < 0] = 0

In [20]:
array = new_data.values

In [21]:
array

array([[2.0160000e+03, 1.0000000e+00, 5.0000000e+00, ..., 9.3687100e+03,
        4.3463490e+04, 1.5943665e+05],
       [2.0130000e+03, 5.0000000e+00, 1.0000000e+00, ..., 6.9319100e+03,
        3.5976940e+04, 1.2005405e+05],
       [2.0150000e+03, 4.0000000e+00, 0.0000000e+00, ..., 8.3511000e+02,
        3.0900400e+03, 1.3868640e+04],
       ...,
       [2.0140000e+03, 4.0000000e+00, 0.0000000e+00, ..., 1.0966900e+03,
        2.3199600e+03, 1.6485340e+04],
       [2.0150000e+03, 4.0000000e+00, 0.0000000e+00, ..., 6.4189500e+03,
        3.4995500e+04, 1.1386136e+05],
       [2.0140000e+03, 2.0000000e+00, 6.0000000e+00, ..., 4.3639000e+02,
        3.1374900e+03, 8.7947500e+03]])

In [22]:
X1 = array[:,0:2]
X2 = array[:, 3:14]
X = np.concatenate((X1, X2), axis=1)

Y = array[:,2]

In [23]:
Y

array([5., 1., 0., ..., 0., 0., 6.])

In [24]:
X

array([[2.0160000e+03, 1.0000000e+00, 3.1100000e+02, ..., 9.3687100e+03,
        4.3463490e+04, 1.5943665e+05],
       [2.0130000e+03, 5.0000000e+00, 7.9000000e+02, ..., 6.9319100e+03,
        3.5976940e+04, 1.2005405e+05],
       [2.0150000e+03, 4.0000000e+00, 5.3500000e+02, ..., 8.3511000e+02,
        3.0900400e+03, 1.3868640e+04],
       ...,
       [2.0140000e+03, 4.0000000e+00, 7.9100000e+02, ..., 1.0966900e+03,
        2.3199600e+03, 1.6485340e+04],
       [2.0150000e+03, 4.0000000e+00, 7.9000000e+02, ..., 6.4189500e+03,
        3.4995500e+04, 1.1386136e+05],
       [2.0140000e+03, 2.0000000e+00, 2.5300000e+02, ..., 4.3639000e+02,
        3.1374900e+03, 8.7947500e+03]])

In [25]:
test = SelectKBest(score_func=chi2, k=10)

In [26]:
fit = test.fit(X, Y)

In [27]:
np.set_printoptions(precision=3)
print(fit.scores_)

[1.803e-01 2.440e+05 1.526e+07 1.985e+05 1.129e+09 1.044e+09 6.312e+08
 1.922e+09 2.672e+08 6.241e+07 7.041e+07 2.704e+08 2.060e+09]

In [28]:
features = fit.transform(X)

In [29]:
print(features[0:6,:])

[[3.110e+02 1.145e+05 0.000e+00 1.500e+03 1.160e+05 2.103e+04 1.307e+04
  9.369e+03 4.346e+04 1.594e+05]
 [7.900e+02 8.408e+04 0.000e+00 0.000e+00 8.408e+04 1.659e+04 1.246e+04
  6.932e+03 3.598e+04 1.201e+05]
 [5.350e+02 9.980e+03 0.000e+00 7.984e+02 1.078e+04 0.000e+00 2.255e+03
  8.351e+02 3.090e+03 1.387e+04]
 [2.500e+02 2.873e+03 0.000e+00 0.000e+00 2.873e+03 0.000e+00 6.226e+02
  2.225e+02 8.451e+02 3.718e+03]
 [7.900e+02 6.702e+03 0.000e+00 1.767e+02 6.879e+03 0.000e+00 2.712e+03
  5.384e+02 3.250e+03 1.013e+04]
 [2.100e+01 4.532e+04 0.000e+00 0.000e+00 4.532e+04 9.386e+03 1.178e+04
  3.486e+03 2.465e+04 6.997e+04]]

In [30]:
for i in fit.scores_:
    print(i)
    j = np.float64(i).astype(str)
    print(i,"---",j)

0.18028126202013464
0.18028126202013464 --- 0.18028126202013464
243987.53135271353
243987.53135271353 --- 243987.53135271353
15264164.782287844
15264164.782287844 --- 15264164.782287844
198519.52899488626
198519.52899488626 --- 198519.52899488626
1128500200.5776718
1128500200.5776718 --- 1128500200.5776718
1044301147.398399
1044301147.398399 --- 1044301147.398399
631240203.8441801
631240203.8441801 --- 631240203.8441801
1922159670.5243876
1922159670.5243876 --- 1922159670.5243876
267241490.49094096
267241490.49094096 --- 267241490.49094096
62409801.475027405
62409801.475027405 --- 62409801.475027405
70413193.95257759
70413193.95257759 --- 70413193.95257759
270442832.25754124
270442832.25754124 --- 270442832.25754124
2060089250.4379735
2060089250.4379735 --- 2060089250.4379735